FROM python

RUN pip install drep

#FROM python

#WORKDIR /dRep_evaluator

#RUN git clone https://github.com/MrOlm/drep.git

#RUN cd drep && pip install -r requirements.txt

#RUN echo "Welcome to dRep container!"